- hosts: localhost
  tasks:
    - name: Ensure the certificates directory exists
      ansible.builtin.file:
        path: ../certificates
        state: directory
        mode: '0755'
    - name: Check if user-ca file exists
      ansible.builtin.stat:
        path: ../certificates/user-ca
      register: user_ca_file

    - name: Generate CA keys
      ansible.builtin.shell: ssh-keygen -t ecdsa -f user-ca
      args:
        chdir: ../certificates
      when: not user_ca_file.stat.exists

    - name: Add CA public key to ca.pub
      ansible.builtin.shell: cat user-ca.pub > ca.pub
      args:
        chdir: ../certificates

    - name: Generate bastion SSH config
      ansible.builtin.template:
        src: ../files/bastion_ssh_config.j2
        dest: /tmp/bastion_ssh
        mode: '0644'
      vars:
        secured_ip: "{{ hostvars['secured'].private_ip }}"

- hosts: bastion
  become: true
  tasks:
    - name: Upload sshd_config
      ansible.builtin.copy:
        src: ../files/bastion_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'

    - name: Upload bastion SSH agent config
      ansible.builtin.copy:
        src: /tmp/bastion_ssh
        dest: /home/ec2-user/.ssh/config
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Upload ssh key for secured instance
      ansible.builtin.copy:
        src: ../terraform/tfkey
        dest: /home/ec2-user/.ssh/secured_key
        owner: ec2-user
        group: ec2-user
        mode: '0400'

    - name: Remove authorized_keys file
      ansible.builtin.file:
        path: /home/ec2-user/.ssh/authorized_keys
        state: absent

    - name: Change SSH port
      ansible.builtin.shell: echo "" >> /etc/ssh/sshd_config && echo "Port 37271" >> /etc/ssh/sshd_config

- hosts: bastion, secured
  become: true
  tasks:
    - name: Upload ca.pub
      ansible.builtin.copy:
        src: ../certificates/ca.pub
        dest: /etc/ssh/ca.pub
        owner: root
        group: root
        mode: '0644'

    - name: Change SSHD to use TrustedUserCAKeys file
      ansible.builtin.shell: echo "" >> /etc/ssh/sshd_config && echo "TrustedUserCAKeys /etc/ssh/ca.pub" >> /etc/ssh/sshd_config

    - name: Restart SSHD service
      ansible.builtin.service:
        name: sshd
        state: restarted
